language: android

env:
  global:
    - ANDROID_BUILD_TOOLS_VERSION=23.0.3
    - ANDROID_SDK_VERSION=23
    - EMULATOR_ANDROID_ABI=armeabi-v7a
    - EMULATOR_ANDROID_SDK_VERSION=23
    - EMULATOR_ANDROID_TARGET=android-tv
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
    - JPM_BIN=${HOME}/jpm/bin
    - JPM_HOME=${HOME}/jpm

android:
  components:
    - tools
    - platform-tools
    - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
    - android-${ANDROID_SDK_VERSION}
    - extra-android-m2repository
    - sys-img-${EMULATOR_ANDROID_ABI}-android-tv-${EMULATOR_ANDROID_SDK_VERSION}

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-${EMULATOR_ANDROID_SDK_VERSION} --abi ${EMULATOR_ANDROID_TARGET}/${EMULATOR_ANDROID_ABI}
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 20
  - adb shell input keyevent 82 &

script:
  - travis_wait 20 ./gradlew clean assemble check connectedCheck -PdisablePreDex

after_success:
  - curl -sL http://bit.ly/jpm4j > jpm4j.jar
  - java -jar jpm4j.jar --home ${JPM_HOME} --bindir ${JPM_BIN} init
  - ${JPM_BIN}/jpm install com.codacy:codacy-coverage-reporter:assembly
  - ${JPM_BIN}/codacy-coverage-reporter --projectToken ${CODACY_PROJECT_TOKEN} --language Java --coverageReport app/build/reports/coverage/debug/report.xml

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
